kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "selenium-runner"
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/leprechaun/selenium-on-openshift"
  strategy:
    type: Docker
    dockerStrategy:
      noCache: true
      dockerfilePath: runner/Dockerfile
  output:
    to:
      kind: "ImageStreamTag"
      name: "selenium-runner:latest"
