kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "selenium-hub"
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/leprechaun/selenium-on-openshift"
  strategy:
    type: Docker
    dockerStragegy:
      noCache: true
      dockerfilePath: hub/
  output:
    to:
      kind: "ImageStreamTag"
      name: "selenium-hub:latest"
