kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "pipeline-selenium-os"
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/leprechaun/selenium-on-openshift"
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfilePath: ./
