apiVersion: v1
kind: DeploymentConfig
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
    name: selenium-hub
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
  replicas: 1
  selector:
    app: selenium-hub
    deploymentconfig: selenium-hub
    name: selenium-hub
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: selenium-hub
        deploymentconfig: selenium-hub
        name: selenium-hub
    spec:
      containers:
        - name: selenium-hub
          image: >-
            172.30.1.1:5000/myproject/selenium-hub:latest
          ports:
            - containerPort: 4444
              protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
