apiVersion: v1
kind: DeploymentConfig
metadata:
  name: selenium
  labels:
    app: selenium
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
  replicas: 1
  selector:
    app: selenium
    deploymentconfig: selenium
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: selenium
        deploymentconfig: selenium
    spec:
      containers:
        - name: selenium-chrome
          image: >-
            172.30.1.1:5000/test-project/selenium-os:latest
          ports:
            - containerPort: 4444
              protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
