apiVersion: v1
kind: Service
metadata:
  name: selenium
  namespace: test-project
spec:
  ports:
    - name: web
      protocol: TCP
      port: 4444
      targetPort: 4444
  selector:
    name: selenium
  type: ClusterIP
  sessionAffinity: None
