apiVersion: v1
kind: Pod
metadata:
  name: selenium-runner
  labels:
    app: selenium-runner
    name: selenium-runner
  namespace: my-project
spec:
  containers:
    - image: 172.30.1.1:5000/my-project/selenium-runner:latest
      imagePullPolicy: Always
      name: selenium-runner
      resources: {}
      env:
        - name: SELENIUM_HUB_HOST
          value: selenium-hub:4444
  restartPolicy: Never
